# Generated by Django 3.1.2 on 2020-10-25 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_jugadores', models.IntegerField(default=0)),
                ('cantidad_partidas_por_jugar', models.IntegerField(default=0)),
                ('cantidad_partidas_jugadas', models.IntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juego', to='Juegos.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador1', models.CharField(max_length=10)),
                ('jugador1_punteo', models.IntegerField(default=0)),
                ('jugador2', models.CharField(max_length=10)),
                ('jugador2_punteo', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('completada', models.BooleanField(default=False)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo', to='Torneos.torneo')),
            ],
        ),
    ]
