# Generated by Django 3.1.2 on 2020-10-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='fase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase',
            field=models.IntegerField(default=0),
        ),
    ]
